import {test} from 'node:test';
import assert from 'node:assert/strict';
import {chunkPages,cosine,lexicalRanks,retrieve,validateClaims,graphSearch,normalized} from '../lib/core';
import type {Chunk,Evidence,Entity,Edge} from '../lib/types';
const chunk=(id:string,text:string,document_id=id,vector=[1,0]):Chunk=>({id,document_id,text,vector,page:1,ordinal:0,section:'Test'});
const corpus=[chunk('a','Nora leads the Atlas project. Atlas uses PostgreSQL.'),chunk('b','Atlas depends on Boreal. Boreal has a security review.'),chunk('c','Boreal follows the access review procedure.'),chunk('d','Garden plants need water.', 'd',[0,1])];
const entities:Entity[]=[{id:'n',label:'Nora',kind:'Person'},{id:'a',label:'Atlas',kind:'Project'},{id:'b',label:'Boreal',kind:'Project'}];
const edges:Edge[]=[{id:'e1',source:'n',target:'a',relation:'LEADS',quote:'Nora leads the Atlas project.',chunk_id:'a'},{id:'e2',source:'a',target:'b',relation:'DEPENDS_ON',quote:'Atlas depends on Boreal.',chunk_id:'b'}];
const mentions=[{entity_id:'n',chunk_id:'a'},{entity_id:'a',chunk_id:'a'},{entity_id:'a',chunk_id:'b'},{entity_id:'b',chunk_id:'b'},{entity_id:'b',chunk_id:'c'}];
test('chunking preserves page and never crosses page boundary',()=>{const c=chunkPages([{page:1,text:'First page. '.repeat(150)},{page:2,text:'Second page. '.repeat(100)}],'doc');assert(c.length>2);assert(c.every(x=>x.text.length<=1100));assert(c.some(x=>x.page===2));assert(c.every(x=>!(x.text.includes('First')&&x.text.includes('Second'))));});
test('overlap keeps boundary evidence available',()=>{const text=Array.from({length:300},(_,i)=>`term${i}`).join(' '),c=chunkPages([{page:1,text}],'d');assert(c[0].text.slice(-80).split(' ').slice(1,-1).some(t=>c[1].text.includes(t)));});
test('null page stays unknown rather than invented',()=>assert.equal(chunkPages([{page:null,text:'A long enough document without physical page numbers.'}],'d')[0].page,null));
test('Unicode normalisation preserves accents and removes punctuation',()=>assert.equal(normalized('École — Atlas!'),'école atlas'));
test('cosine rejects incompatible dimensions',()=>assert.equal(cosine([1,2],[1]),0));
test('cosine handles zero norm',()=>assert.equal(cosine([0,0],[1,2]),0));
test('cosine exact and orthogonal comparisons',()=>{assert.equal(cosine([1,0],[1,0]),1);assert.equal(cosine([1,0],[0,1]),0);});
test('lexical retrieval rejects no-overlap question',()=>assert.equal(lexicalRanks('quantum galaxies',corpus).length,0));
test('lexical ranking finds exact technical term',()=>assert.equal(lexicalRanks('PostgreSQL',corpus)[0].id,'a'));
test('graph follows evidenced two-hop paths',()=>{const r=graphSearch('Nora',entities,edges,mentions);assert(r.paths.some(p=>p.entities.join(',')==='n,a,b'));assert(r.ranked.some(c=>c.id==='c'));});
test('unknown graph entity returns no invented path',()=>assert.equal(graphSearch('Zephyr',entities,edges,mentions).paths.length,0));
test('graph retains direction even when traversed in reverse',()=>{const p=graphSearch('Boreal',entities,edges,mentions).paths.find(p=>p.edges[0]?.id==='e2');assert.equal(p?.edges[0].source,'a');assert.equal(p?.edges[0].target,'b');});
test('hybrid fuses genuine branches and returns mapped citations',()=>{const r=retrieve('Nora Atlas','hybrid',corpus,[1,0],entities,edges,mentions);assert.equal(r.sources[0].id,'a');assert.deepEqual(r.sources[0].branches,['lexical','vector','graph']);assert.equal(r.sources[0].citation,'S1');});
test('graph paths shown only when every edge source is retrieved',()=>{const r=retrieve('PostgreSQL','lexical',corpus,[],entities,edges,mentions);assert(r.paths.every(p=>p.edges.every(e=>r.sources.some(s=>s.id===e.chunk_id))));});
const evidence:Evidence[]=[{...corpus[0],citation:'S1',score:1,branches:['lexical']}];
test('valid claim requires a matching quotation',()=>{const r=validateClaims({claims:[{text:'Nora leads Atlas.',citations:['S1'],quotes:['Nora leads the Atlas project.']}]},evidence);assert.equal(r.abstained,false);assert.match(r.answer,/\[S1\]/);});
test('fabricated citation rejected',()=>assert.equal(validateClaims({claims:[{text:'Nora leads Atlas.',citations:['S999'],quotes:['Nora leads the Atlas project.']}]},evidence).abstained,true));
test('fabricated quotation rejected',()=>assert.equal(validateClaims({claims:[{text:'Nora leads Atlas.',citations:['S1'],quotes:['Nora leads the Boreal project.']}]},evidence).abstained,true));
test('empty evidence abstains',()=>assert.equal(validateClaims({claims:[]},[]).abstained,true));
test('untrusted citation markup is replaced by validated identifiers',()=>{const r=validateClaims({claims:[{text:'Nora leads Atlas. [S999]',citations:['S1'],quotes:['Nora leads the Atlas project.']}]},evidence);assert(!r.answer.includes('S999'));});
test('partially malformed output removes invalid claims',()=>{const r=validateClaims({claims:[{text:'Nora leads Atlas.',citations:['S1'],quotes:['Nora leads the Atlas project.']},{text:'Bad',citations:[]}]},evidence);assert.equal(r.rejected,1);assert.equal(r.abstained,false);});
