'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {ArrowUp,ArrowUpRight,BookOpen,Network,Users,Plus,FileText,Search,Trash2,Download,ChevronRight,MessageSquare,History,Loader2,ShieldCheck,Check,X,Link2,SlidersHorizontal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetHeader} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,SidebarInset} from '@/components/ui/sidebar';
import type {Answer,Mode,Entity,Edge,Evidence} from '@/lib/types';
import {parseFile} from '@/lib/parse-file';
const views=[{id:'ask',label:'Ask your knowledge',icon:MessageSquare},{id:'library',label:'Document library',icon:BookOpen},{id:'graph',label:'Knowledge graph',icon:Network},{id:'experts',label:'People & expertise',icon:Users},{id:'history',label:'Query history',icon:History}] as const;
const modes:Record<Mode,string>={hybrid:'Hybrid GraphRAG',vector:'Semantic search',lexical:'Keyword search',graph:'Graph search'};
type Doc={id:string;title:string;filename:string;chunks:number;characters:number;created_at:string;extraction:string};
type Graph={entities:(Entity&{mentions?:number})[];edges:(Edge&{document_id:string;title:string;page:number|null})[]};
async function api(path:string,options?:RequestInit){const r=await fetch(path,options);let data:any;try{data=await r.json();}catch{throw new Error('The server returned an unexpected response. Please retry.');}if(!r.ok)throw new Error(data.error||'The request failed.');return data;}
export default function Workspace(){
 const[view,setView]=useState<string>('ask'),[documents,setDocuments]=useState<Doc[]>([]),[graph,setGraph]=useState<Graph>({entities:[],edges:[]}),[history,setHistory]=useState<Answer[]>([]),[experts,setExperts]=useState<any[]>([]),[ready,setReady]=useState(false),[model,setModel]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[question,setQuestion]=useState(''),[mode,setMode]=useState<Mode>('hybrid'),[answer,setAnswer]=useState<Answer|null>(null),[asking,setAsking]=useState(false),[upload,setUpload]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[ocr,setOCR]=useState(false),[files,setFiles]=useState<File[]>([]),[search,setSearch]=useState(''),[selectedNode,setSelectedNode]=useState<string|null>(null),[source,setSource]=useState<any>(null),[deleting,setDeleting]=useState<Doc|null>(null),[clearing,setClearing]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),queryRef=useRef<HTMLTextAreaElement>(null);
 const refresh=useCallback(async()=>{const[d,g,h,e,s]=await Promise.all([api('/api/documents'),api('/api/graph'),api('/api/history'),api('/api/experts'),api('/api/health')]);setDocuments(d.documents);setGraph(g);setHistory(h.history);setExperts(e.experts);setModel(s.modelConfigured);setReady(true);},[]);
 useEffect(()=>{refresh().catch(e=>{setError(e.message);setReady(true);});},[refresh]);
 function changeView(v:string){setView(v);setSearch('');setSelectedNode(null);setError('');}
 async function submit(){if(asking||!question.trim())return;setAsking(true);setError('');setAnswer(null);try{const a=await api('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,mode})});setAnswer(a);setHistory(h=>[a,...h].slice(0,30));}catch(e:any){setError(e.message);}finally{setAsking(false);}}
 async function importFiles(){setBusy(true);setError('');let imported=0;try{for(const file of files){setProgress(`Reading ${file.name}`);const parsed=await parseFile(file,ocr,setProgress);setProgress(`Indexing ${file.name}: embeddings and knowledge graph`);const form=new FormData();form.append('file',file);form.append('pages',JSON.stringify(parsed.pages));form.append('title',file.name.replace(/\.[^.]+$/,''));form.append('extraction',parsed.method);const result=await api('/api/documents',{method:'POST',body:form});if(!result.duplicate)imported++;}await refresh();setFiles([]);setUpload(false);setNotice(`${imported} document${imported===1?'':'s'} added. Duplicate files were skipped.`);}catch(e:any){setError(e.message);await refresh().catch(()=>{});}finally{setBusy(false);setProgress('');}}
 async function inspectDocument(id:string){try{const data=await api(`/api/documents/${id}`);setSource({kind:'document',...data});}catch(e:any){setError(e.message);}}
 async function removeDocument(){if(!deleting)return;setBusy(true);try{await api(`/api/documents/${deleting.id}`,{method:'DELETE'});setAnswer(null);setDeleting(null);await refresh();setNotice('Document, graph evidence and saved query history deleted.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const totalChunks=documents.reduce((n,d)=>n+d.chunks,0),filteredDocs=documents.filter(d=>d.title.toLowerCase().includes(search.toLowerCase())),nodes=graph.entities.filter(e=>e.label.toLowerCase().includes(search.toLowerCase())).slice(0,35),nodeMap=new Map(graph.entities.map(e=>[e.id,e])),displayEdges=graph.edges.filter(e=>(!selectedNode||e.source===selectedNode||e.target===selectedNode)&&(!search||nodeMap.get(e.source)?.label.toLowerCase().includes(search.toLowerCase())||nodeMap.get(e.target)?.label.toLowerCase().includes(search.toLowerCase())));
 return <SidebarProvider style={{'--sidebar-width':'15.5rem'} as React.CSSProperties}>
 <Sidebar className="n6-sidebar"><SidebarHeader><button className="brand" onClick={()=>changeView('ask')} aria-label="N6 home">N<span>6</span><small>KNOWLEDGE</small></button></SidebarHeader>
 <SidebarContent><div className="workspace-label">YOUR WORKSPACE</div><SidebarMenu>{views.map(v=><SidebarMenuItem key={v.id}><SidebarMenuButton isActive={view===v.id} onClick={()=>changeView(v.id)} className="nav-item"><v.icon/><span>{v.label}</span>{v.id==='library'&&<b>{documents.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>
 <div className="sidebar-divider"/><div className="sidebar-note"><p>Connected knowledge.<br/>Traceable answers.</p><span>Every answer starts<br/>with your documents.</span></div>
 </SidebarContent><SidebarFooter><div className="identity"><div>AK</div><p>Ahmed Khalil<small>Private workspace</small></p><ShieldCheck size={17}/></div></SidebarFooter></Sidebar>
 <SidebarInset className="main-surface"><header className="topbar"><div><SidebarTrigger/><span className="muted">Workspace</span><ChevronRight size={14}/><span>{views.find(v=>v.id===view)?.label}</span></div><Button className="upload-button" onClick={()=>{setUpload(true);setError('');}}><Plus/>Add documents</Button></header>
 <main id="main-content" className={`content ${view==='ask'?'ask-content':''}`}>
 {error&&<div role="alert" className="message error"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {notice&&<div role="status" className="message"><span>{notice}</span><button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {view==='ask'&&<>
 <div className={`ask-intro ${answer?'compact':''}`}><div className="eyebrow"><span className="n6-mark">✳</span> EXPLORE YOUR KNOWLEDGE</div><h1>Good questions deserve <br/><em>grounded answers.</em></h1><p>Ask across your documents. Follow the evidence.<br className="mobile-hide"/> Discover how your knowledge connects.</p></div>
 <form className="question-box" onSubmit={e=>{e.preventDefault();submit();}}><label className="sr-only" htmlFor="question">Your question</label><Textarea ref={queryRef} id="question" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} placeholder={documents.length?'What would you like to understand?':'Add your documents, then ask a question…'} onKeyDown={e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();submit();}}}/><div className="query-controls"><Select value={mode} onValueChange={v=>setMode(v as Mode)}><SelectTrigger aria-label="Retrieval method"><Network size={15}/><SelectValue/></SelectTrigger><SelectContent>{Object.entries(modes).map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select><Button type="submit" className="ask-button" aria-label="Ask question" disabled={asking||!question.trim()||!documents.length||!model}>{asking?<Loader2 className="spin"/>:<ArrowUp size={20}/>}</Button></div></form>
 <div className="under-query"><span>{ready?`${documents.length} documents · ${totalChunks} passages`:'Connecting to workspace…'}</span><span><ShieldCheck size={13}/> Sources included with every answer</span></div>
 {asking&&<div className="thinking" role="status"><Loader2 className="spin" size={18}/><div>Reading your knowledge<p>Retrieving passages, following relationships, and checking citations.</p></div></div>}
 {answer&&<section className="answer-layout"><article className="answer"><div className="answer-header"><span className="eyebrow">{answer.abstained?'INSUFFICIENT EVIDENCE':'GROUNDED RESPONSE'}</span><span>{(answer.durationMs/1000).toFixed(1)}s</span></div><h2>{answer.question}</h2>{answer.answer.split('\n\n').map((p,i)=><p className="answer-paragraph" key={i}>{p.split(/(\[S\d+\])/g).map((t,j)=>/^\[S\d+\]$/.test(t)?<button className="citation" key={j} onClick={()=>setSource({kind:'passage',passage:answer.sources.find(s=>`[${s.citation}]`===t)})}>{t.slice(1,-1)}</button>:t)}</p>)}{answer.warnings.map(w=><p className="warning" key={w}>{w}</p>)}<details className="workflow"><summary>How this answer was built</summary><ol>{answer.steps.map(s=><li key={s}>{s}</li>)}</ol><p>Citation checks confirm source IDs and matching quotations. Review the sources to assess whether each claim is fully supported.</p>{answer.paths.length>0&&<><h3>Graph paths in the evidence</h3>{answer.paths.map((p,i)=><p key={i}>{p.entities.map(id=>nodeMap.get(id)?.label||'Entity').join(' → ')}</p>)}</>}</details></article><aside className="source-list"><h3>Sources <span>{answer.sources.length}</span></h3>{answer.sources.map(s=><button key={s.id} onClick={()=>setSource({kind:'passage',passage:s})}><span className="source-number">{s.citation}</span><strong>{s.title}</strong><small>{s.page?`Page ${s.page}`:`Passage ${s.ordinal+1}`} · {s.branches.join(' + ')}</small><p>{s.text.slice(0,140)}…</p></button>)}</aside></section>}
 {!answer&&!asking&&<section className="start-panel">{!documents.length?<><div className="start-illustration"><BookOpen size={32} strokeWidth={1}/></div><h2>Your knowledge begins here</h2><p>Add reports, procedures, or project notes.<br/>N6 will organise their concepts and connections.</p><Button variant="outline" onClick={()=>setUpload(true)}><Plus/>Add your first document</Button><span className="filetypes">PDF, DOCX, TXT, MD, CSV, JSON</span></>:<><div className="section-line"><span>A PLACE TO START</span><span>{graph.entities.length} concepts connected</span></div><div className="question-suggestions">{['Which people are responsible for the projects in these documents?','What relationships connect the main organisations?','Which procedures or documents discuss similar topics?'].map(q=><button key={q} onClick={()=>{setQuestion(q);queryRef.current?.focus();}}><span>{q}</span><ArrowUpRight size={18}/></button>)}</div></>}</section>}
 </>}
 {view==='library'&&<><div className="page-heading"><div className="eyebrow">THE SOURCE OF YOUR ANSWERS</div><h1>Document library</h1><p>Original documents and the passages that make them searchable.</p></div><div className="section-toolbar"><label className="search-box"><Search size={17}/><Input aria-label="Search documents" placeholder="Find a document…" value={search} onChange={e=>setSearch(e.target.value)}/></label><span className="muted">{documents.length} documents · {totalChunks} passages</span></div>{!documents.length?<Empty icon={BookOpen} title="A library of your own" text="Add documents to start building a connected knowledge base." action={()=>setUpload(true)}/>:<div className="document-list">{filteredDocs.map(d=><article className="document-row" key={d.id}><div className="file-icon"><FileText size={23}/></div><button className="document-name" onClick={()=>inspectDocument(d.id)}><strong>{d.title}</strong><span>{d.filename.split('.').pop()?.toUpperCase()} · {d.chunks} passages · Added {new Date(d.created_at).toLocaleDateString('en-GB')}</span></button><span className="ready-state"><Check size={13}/>Indexed</span><Button size="icon" variant="ghost" aria-label={`Download ${d.title}`} asChild><a href={`/api/documents/${d.id}?download=1`}><Download size={17}/></a></Button><Button size="icon" variant="ghost" aria-label={`Delete ${d.title}`} onClick={()=>setDeleting(d)}><Trash2 size={17}/></Button></article>)}{filteredDocs.length===0&&<p className="empty-inline">No matching documents.</p>}</div>}<div className="privacy-note"><ShieldCheck size={18}/><p>Documents stay in your private workspace. Text is sent to NVIDIA to create embeddings, extract relationships, and answer questions. Only upload documents you are allowed to process.</p></div></>}
 {view==='graph'&&<><div className="page-heading"><div className="eyebrow">LOOK BEYOND INDIVIDUAL DOCUMENTS</div><h1>Knowledge graph</h1><p>Explore entities and the source passages that connect them.</p></div><div className="section-toolbar"><label className="search-box"><Search size={17}/><Input aria-label="Find an entity" placeholder="Find an entity…" value={search} onChange={e=>setSearch(e.target.value)}/></label><Button variant="outline" asChild><a href="/api/export" download="n6-knowledge-graph.json"><Download/>Export graph</a></Button></div>{graph.entities.length?<><div className="graph-stats"><span>{graph.entities.length} entities</span><span>{graph.edges.length} evidenced relationships</span><span>Showing up to 35 entities</span></div><div className="graph-canvas"><svg viewBox="0 0 1000 630" role="img" aria-label="Knowledge graph. Select an entity below to inspect its connections."><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="20" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#bbb9ae"/></marker></defs>{graph.edges.filter(e=>nodes.some(n=>n.id===e.source)&&nodes.some(n=>n.id===e.target)).slice(0,90).map(e=>{const i=nodes.findIndex(n=>n.id===e.source),j=nodes.findIndex(n=>n.id===e.target),a=position(i,nodes.length),b=position(j,nodes.length);return <line key={e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={selectedNode===e.source||selectedNode===e.target?'#b56a4d':'#d6d3c9'} strokeWidth="1.4" markerEnd="url(#arrow)"/>;})}{nodes.map((n,i)=>{const p=position(i,nodes.length);return <g key={n.id} onClick={()=>setSelectedNode(n.id===selectedNode?null:n.id)} className="graph-node" transform={`translate(${p.x},${p.y})`}><circle r={n.id===selectedNode?12:8} fill={n.kind==='Person'?'#788978':n.kind==='Organization'?'#b66c50':'#343830'}/><text y="25" textAnchor="middle">{n.label.length>25?n.label.slice(0,23)+'…':n.label}</text></g>;})}</svg></div><div className="entity-choices">{nodes.map(n=><button key={n.id} className={selectedNode===n.id?'selected':''} onClick={()=>setSelectedNode(n.id===selectedNode?null:n.id)}>{n.label}<span>{n.kind}</span></button>)}</div><div className="section-line"><h2>{selectedNode?`Connections: ${nodeMap.get(selectedNode)?.label}`:'Relationship evidence'}</h2>{selectedNode&&<button onClick={()=>setSelectedNode(null)}>Clear selection</button>}</div><div className="relation-list">{displayEdges.slice(0,30).map(e=><button key={e.id} onClick={()=>setSource({kind:'edge',edge:e,from:nodeMap.get(e.source)?.label,to:nodeMap.get(e.target)?.label})}><span>{nodeMap.get(e.source)?.label}</span><small>{e.relation.replaceAll('_',' ').toLowerCase()}</small><span>{nodeMap.get(e.target)?.label}</span><ArrowUpRight size={16}/></button>)}{!displayEdges.length&&<p>No evidenced relationships for this selection.</p>}</div></>:<Empty icon={Network} title="See the connections" text="Entities and supported relationships appear after documents are indexed." action={()=>setUpload(true)}/>}</>}
 {view==='experts'&&<><div className="page-heading"><div className="eyebrow">KNOWLEDGE HAS PEOPLE BEHIND IT</div><h1>People & expertise</h1><p>Find people with documented responsibilities and domain connections.</p></div><div className="privacy-note"><Users size={18}/><p>These are candidates supported by document evidence, not verified expertise ratings. Check responsibilities and source dates before contacting anyone.</p></div>{experts.length?<div className="expert-list">{experts.map((e,i)=><article key={i}><div className="person-initials">{e.label.split(' ').map((w:string)=>w[0]).slice(0,2).join('')}</div><div><h2>{e.label}</h2><p>{e.relation.replaceAll('_',' ').toLowerCase()} <strong>{e.topic}</strong></p><blockquote>{e.quote}</blockquote><button className="text-link" onClick={()=>inspectDocument(e.document_id)}><FileText size={14}/>{e.title}{e.page?` · p. ${e.page}`:''}<ArrowUpRight size={14}/></button></div></article>)}</div>:<Empty icon={Users} title="Find the people behind the work" text="Profiles appear when documents explicitly connect a person to a responsibility, project, or field."/>}</>}
 {view==='history'&&<><div className="page-heading"><div className="eyebrow">RETURN TO YOUR RESEARCH</div><h1>Query history</h1><p>Your latest 30 questions, with their evidence preserved.</p></div>{history.length?<><div className="section-toolbar"><span>{history.length} saved queries</span><Button variant="outline" onClick={()=>setClearing(true)}><Trash2/>Clear history</Button></div><div className="history-list">{history.map(a=><button key={a.id} onClick={()=>{setAnswer(a);setQuestion(a.question);setView('ask');}}><MessageSquare size={19}/><span><strong>{a.question}</strong><small>{modes[a.mode]} · {a.sources.length} sources · {new Date(a.created_at).toLocaleString('en-GB')}</small></span><ArrowUpRight size={18}/></button>)}</div></>:<Empty icon={History} title="A record of your questions" text="Your questions and cited answers will appear here."/>}</>}
 </main><footer className="workspace-footer"><span>N6 / Enterprise Knowledge</span><span>Knowledge Graph + LLM</span></footer></SidebarInset>
 <Dialog open={upload} onOpenChange={v=>{if(!busy)setUpload(v);}}><DialogContent className="upload-dialog"><DialogHeader><DialogTitle>Add to your knowledge</DialogTitle><DialogDescription>Documents are processed with NVIDIA models. Only upload material you have permission to use.</DialogDescription></DialogHeader><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)setFiles(Array.from(e.dataTransfer.files).slice(0,5));}}><FileText size={30} strokeWidth={1.2}/><p>Drop documents here</p><span>PDF, DOCX, TXT, MD, CSV or JSON<br/>Up to 8 MB and 40,000 characters per file</span><Button variant="outline" disabled={busy} onClick={()=>fileInput.current?.click()}>Choose files</Button><input ref={fileInput} type="file" className="sr-only" multiple accept=".pdf,.docx,.txt,.md,.csv,.json" onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,5))}/></div>{files.length>0&&<ul className="selected-files">{files.map(f=><li key={f.name}><FileText size={15}/><span>{f.name}</span><small>{(f.size/1024).toFixed(0)} KB</small></li>)}</ul>}<label className="ocr-option"><input type="checkbox" checked={ocr} disabled={busy} onChange={e=>setOCR(e.target.checked)}/><span>Use OCR for scanned PDF pages<small>English recognition runs in your browser. Scans take longer.</small></span></label>{progress&&<div className="upload-progress" role="status"><Loader2 className="spin" size={16}/>{progress}</div>}{error&&<p role="alert" className="warning">{error}</p>}<Button className="full-button" disabled={!files.length||busy} onClick={importFiles}>{busy?'Building your knowledge…':`Index ${files.length||''} document${files.length===1?'':'s'}`}<ArrowUpRight/></Button></DialogContent></Dialog>
 <Sheet open={!!source} onOpenChange={v=>{if(!v)setSource(null);}}><SheetContent className="evidence-sheet"><SheetHeader><SheetTitle>{source?.kind==='passage'?source.passage?.title:source?.kind==='document'?source.document?.title:'Relationship evidence'}</SheetTitle><SheetDescription>Inspect the source before relying on a claim.</SheetDescription></SheetHeader><div className="evidence-body">{source?.kind==='passage'&&<><div className="eyebrow">{source.passage?.citation} · {source.passage?.page?`PAGE ${source.passage.page}`:`PASSAGE ${(source.passage?.ordinal||0)+1}`}</div><blockquote>{source.passage?.text}</blockquote><Button variant="outline" onClick={()=>inspectDocument(source.passage.document_id)}>Open full document record<ArrowUpRight/></Button></>}{source?.kind==='document'&&<><p className="muted">{source.document.extraction}</p><Button asChild variant="outline"><a href={`/api/documents/${source.document.id}?download=1`}><Download/>Download original</a></Button><RelatedDocuments id={source.document.id} onOpen={inspectDocument}/>{source.passages.map((p:any)=><section className="passage" key={p.id}><h3>{p.page?`Page ${p.page}`:`Passage ${p.ordinal+1}`}<span>{p.section}</span></h3><p>{p.text}</p></section>)}<small className="hash">SHA-256: {source.document.sha}</small></>}{source?.kind==='edge'&&<><h2>{source.from} → {source.to}</h2><p>{source.edge.relation.replaceAll('_',' ').toLowerCase()}</p><blockquote>{source.edge.quote}</blockquote><Button variant="outline" onClick={()=>inspectDocument(source.edge.document_id)}>{source.edge.title}<ArrowUpRight/></Button></>}</div></SheetContent></Sheet>
 <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!busy)setDeleting(null);}}><AlertDialogContent><AlertDialogTitle>Delete this document?</AlertDialogTitle><AlertDialogDescription>This removes “{deleting?.title}”, its passages, graph evidence, and your saved query history. Other documents remain available.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();removeDocument();}}>Delete document</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={clearing} onOpenChange={setClearing}><AlertDialogContent><AlertDialogTitle>Clear query history?</AlertDialogTitle><AlertDialogDescription>Your documents and knowledge graph will remain available.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={async()=>{try{await api('/api/history',{method:'DELETE'});setHistory([]);setAnswer(null);}catch(e:any){setError(e.message);}}}>Clear history</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>;
}
function position(i:number,n:number){const angle=(i/Math.max(1,n))*Math.PI*2-Math.PI/2,r=i%3===0?190:245;return{x:500+Math.cos(angle)*r*1.48,y:310+Math.sin(angle)*r};}
function Empty({icon:Icon,title,text,action}:{icon:any;title:string;text:string;action?:()=>void}){return <div className="empty-state"><Icon size={36} strokeWidth={1.2}/><h2>{title}</h2><p>{text}</p>{action&&<Button variant="outline" onClick={action}><Plus/>Add documents</Button>}</div>;}
function RelatedDocuments({id,onOpen}:{id:string;onOpen:(id:string)=>void}){const[items,setItems]=useState<any[]>([]);useEffect(()=>{api(`/api/recommendations?id=${encodeURIComponent(id)}`).then(d=>setItems(d.documents)).catch(()=>setItems([]));},[id]);if(!items.length)return null;return <div className="related"><h3>Related documents</h3>{items.map(d=><button key={d.id} onClick={()=>onOpen(d.id)}>{d.title}<small>{d.shared_entities} shared entities</small><ArrowUpRight size={14}/></button>)}</div>;}
