import {env} from 'cloudflare:workers';
import {timingSafeEqual} from 'node:crypto';
type Runtime={DB:D1Database;FILES:R2Bucket;NVIDIA_API_KEY?:string;NVIDIA_CHAT_MODEL?:string;NVIDIA_EMBED_MODEL?:string;INGEST_TOKEN?:string;INGEST_OWNER_ID?:string};
export const runtime=()=>env as unknown as Runtime;
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export function owner(request:Request):string{const header=request.headers.get('oai-authenticated-user-id');if(header)return header;const e=runtime(),token=request.headers.get('authorization')?.replace(/^Bearer /,'');if(e.INGEST_TOKEN&&e.INGEST_OWNER_ID&&token&&request.method==='POST'&&new URL(request.url).pathname==='/api/documents'){const a=Buffer.from(token),b=Buffer.from(e.INGEST_TOKEN);if(a.length===b.length&&timingSafeEqual(a,b))return e.INGEST_OWNER_ID;}throw new HttpError(401,'Sign in to access your knowledge workspace.');}
export function checkOrigin(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new HttpError(403,'Cross-origin requests are not allowed.');}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin'}});}
export function failure(error:unknown){const known=error instanceof HttpError;console.error('n6_request_failed',{type:known?'request':'internal',status:known?error.status:500});return json({error:known?error.message:'The operation could not complete. Please retry; your existing documents are unchanged.'},known?error.status:500);}
export async function rateLimit(user:string,action:string,max:number){const db=runtime().DB,minute=Math.floor(Date.now()/60000),id=`${user}:${action}:${minute}`,row=await db.prepare('INSERT INTO limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(id,minute+2).first<{count:number}>();if((row?.count||0)>max)throw new HttpError(429,'Too many requests. Please wait one minute and try again.');await db.prepare('DELETE FROM limits WHERE expires < ?').bind(minute).run();}
export async function rows<T>(sql:string,...params:unknown[]):Promise<T[]>{const result=await runtime().DB.prepare(sql).bind(...params).all<T>();return result.results;}
export async function digest(text:string|ArrayBuffer){const b=typeof text==='string'?new TextEncoder().encode(text):text;return[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');}
