import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const documents = sqliteTable('documents', {
 id:text('id').primaryKey(),owner:text('owner').notNull(),title:text('title').notNull(),filename:text('filename').notNull(),mime:text('mime').notNull(),sha:text('sha').notNull(),storageKey:text('storage_key').notNull(),status:text('status').notNull(),chunks:integer('chunks').notNull().default(0),characters:integer('characters').notNull(),embeddingModel:text('embedding_model').notNull(),createdAt:text('created_at').notNull(),extraction:text('extraction').notNull(),
},t=>[uniqueIndex('documents_owner_sha').on(t.owner,t.sha),index('documents_owner').on(t.owner)]);
export const chunks=sqliteTable('chunks',{
 id:text('id').primaryKey(),owner:text('owner').notNull(),documentId:text('document_id').notNull().references(()=>documents.id,{onDelete:'cascade'}),ordinal:integer('ordinal').notNull(),page:integer('page'),section:text('section').notNull(),text:text('text').notNull(),vector:text('vector').notNull(),
},t=>[index('chunks_owner_document').on(t.owner,t.documentId)]);
export const entities=sqliteTable('entities',{id:text('id').primaryKey(),owner:text('owner').notNull(),label:text('label').notNull(),kind:text('kind').notNull()},t=>[index('entities_owner').on(t.owner)]);
export const mentions=sqliteTable('mentions',{id:text('id').primaryKey(),owner:text('owner').notNull(),entityId:text('entity_id').notNull().references(()=>entities.id,{onDelete:'cascade'}),chunkId:text('chunk_id').notNull().references(()=>chunks.id,{onDelete:'cascade'})},t=>[index('mentions_owner_entity').on(t.owner,t.entityId)]);
export const edges=sqliteTable('edges',{id:text('id').primaryKey(),owner:text('owner').notNull(),source:text('source').notNull().references(()=>entities.id,{onDelete:'cascade'}),target:text('target').notNull().references(()=>entities.id,{onDelete:'cascade'}),relation:text('relation').notNull(),quote:text('quote').notNull(),chunkId:text('chunk_id').notNull().references(()=>chunks.id,{onDelete:'cascade'})},t=>[index('edges_owner_source').on(t.owner,t.source),index('edges_owner_target').on(t.owner,t.target)]);
export const queries=sqliteTable('queries',{id:text('id').primaryKey(),owner:text('owner').notNull(),question:text('question').notNull(),response:text('response').notNull(),mode:text('mode').notNull(),createdAt:text('created_at').notNull()},t=>[index('queries_owner').on(t.owner)]);
export const limits=sqliteTable('limits',{id:text('id').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
